[general]
import = ["/home/dk/.config/alacritty/themes/moonfly.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraMono Nerd Font"

[font.offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.95
dynamic_padding = true
