theme = "tsodish"

[editor]
bufferline = "always"
line-number = "relative"
auto-completion = true
auto-save = true
auto-format = true
text-width = 80
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
soft-wrap.enable = true
soft-wrap.max-indent-retain = 80

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner",
  "file-modification-indicator",
  "read-only-indicator",
]
center = ["file-name"]
right = [
  "diagnostics",
  "register",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[keys.normal]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
