# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-fce2431b-8052-4449-a15b-16196a7ccf6a".device = "/dev/disk/by-uuid/fce2431b-8052-4449-a15b-16196a7ccf6a";

  fileSystems."/" =
    { device = "/dev/mapper/luks-5eefa20b-1dce-41a2-be53-115a5a6f6b38";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5eefa20b-1dce-41a2-be53-115a5a6f6b38".device = "/dev/disk/by-uuid/5eefa20b-1dce-41a2-be53-115a5a6f6b38";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B3C2-FB78";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fce2431b-8052-4449-a15b-16196a7ccf6a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
