# Author: typable <contact@typable.dev>

"type" = { fg = "base0A", modifiers = [] }
"constructor" = "base0D"
"constant" = { fg = "base0A" }
"constant.builtin.boolean" = "base09"
"constant.numeric" = "base0A"
"string"  = "base0B"
"string.special" = { modifiers = ["underlined"] } #.path / .url / .symbol
"comment" = { fg = "#777777" }
"variable" = "base08"
"variable.other.member" = "base0D"
"label" = "base0D"
"keyword" = { fg = "base0E" }
"operator" = "base05"
"function" = "base0D"
"function.macro" = { fg = "base0D" }
# "function.special" = { fg = "base01" }
"tag" = { fg = "yellow" }
"special" = "base0D"
"namespace" = "base05"
# "markup" = { fg = "purple" } # .bold / .italic / .quote
"markup.heading" = "base0D"
# "markup.heading.1" = { fg = "orange" }
# "markup.heading.2" = { fg = "yellow" }
# "markup.heading.3" = { fg = "pink" }
# "markup.heading.4" = { fg = "purple" }
# "markup.heading.5" = { fg = "green" }
# "markup.heading.6" = { fg = "blue" }
"markup.list" = "base08"
"markup.link" = "base08"
"markup.raw" = "base0B"
"diff.plus" = "base0B"
"diff.minus" = "base08"
"diff.delta" = "base09"

"ui.background" = { bg = "#000000" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
# "ui.cursor.match" = { fg = "light", bg = "blue_accent" } # .insert / .select / .match / .primary
"ui.cursorline" = { bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "#000000" }
"ui.linenr.selected" = { fg = "base04", bg = "base01" }
"ui.statusline" = { fg = "base04", bg = "base01" }
# "ui.statusline.inactive" = { fg = "dark", bg = "darker" } # .inactive / .normal / .insert / .select
# "ui.statusline.normal" = { fg = "lightest", bg = "darker"} # .inactive / .normal / .insert / .select
# "ui.statusline.insert" = { fg = "lightest", bg = "blue_accent" } # .inactive / .normal / .insert / .select
# "ui.statusline.select" = { fg = "lightest", bg = "orange_accent" } # .inactive / .normal / .insert / .select
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.text" = "base05"
"ui.virtual" = "base03"
"ui.virtual.ruler" = { bg = "base01"}
"ui.virtual.indent-guide" = { fg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.selection" = { bg = "base02" }
# "ui.selection.primary" = { bg = "select" } # .primary
"hint" = "#eeeeee"
"info" = "#777777"
"warning" = "base0E"
"error" = "#e03529"
"diagnostic" = { modifiers = ["underlined"] }

[palette]
base00 = "#181818" # Default Background
base01 = "#222222" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#383838" # Selection Background
base03 = "#333333" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#bbbbbb" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#bbbbbb" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ffffff" # Classes, Markup Bold, Search Text Background
base0B = "#7cb654" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#a5afc0" # Functions, Methods, Attribute IDs, Headings
base0E = "#ffdd47" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
